//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPWithoutWAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessToken
    {
        public int UserID { get; set; }
        public string Token { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.DateTime> DeadTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
