//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPWithoutWAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat_Meta
    {
        public int ChatMetaID { get; set; }
        public int ChatID { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    
        public virtual Chat Chat { get; set; }
    }
}
