//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPWithoutWAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMembers
    {
        public int ChatMembersID { get; set; }
        public int ChatID { get; set; }
        public int UserID { get; set; }
        public int InvitingUser { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Chat Chat { get; set; }
    }
}
