//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPWithoutWAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesages
    {
        public int MessageID { get; set; }
        public int ChatID { get; set; }
        public int AuthorID { get; set; }
        public string MessageText { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual Chat Chat { get; set; }
    }
}
