//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPWithoutWAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessageDBContainer1 : DbContext
    {
        public MessageDBContainer1()
            : base("name=MessageDBContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<User_Meta> User_MetaSet { get; set; }
        public virtual DbSet<Chat> ChatSet { get; set; }
        public virtual DbSet<ChatMembers> ChatMembersSet { get; set; }
        public virtual DbSet<Mesages> MesagesSet { get; set; }
        public virtual DbSet<Chat_Meta> Chat_MetaSet { get; set; }
    }
}
