//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPWithoutWAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Meta
    {
        public int UserMetaID { get; set; }
        public int UserID { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    
        public virtual User User { get; set; }
    }
}
